package leo.modules.output.LPoutput

import leo.Out
import leo.datastructures.{LitNorm, Literal, LiteralInfo, LiteralTransformation}
import leo.modules.output.LPoutput.LpLibs.EqRules.AsTerms.{lpSimp_eqBot, lpSimp_eqTop, lpSimp_negEqBot}
import leo.modules.output.LPoutput.LpLibs.ND.Terms.eqSym
import leo.modules.output.LPoutput.LpTacticUtil.PatternBuilder
import leo.modules.output.LPoutput.NewLpDatastructures.LpProofScript.{Rewrite, Side}
import leo.modules.output.LPoutput.NewLpDatastructures.{Level, LpTerm}

object ImplicitTransformationUtil {

  // Literal Normalisazion

  /**
    * LiteralInfo2LiteralTransformation — Reindex literal transformations
    *
    * Converts input LiteralInfo sequence, which describes transformations relative
    * to a freshly generated block of literals, into a global
    * LiteralTransformation instance suitable for clause-level rewriting.
    *
    * Notes:
    * • This function performs only index translation, it does NOT validate
    * transformation consistency or clause bounds.
    *
    * @param litInfo Transformation metadata relative to generated literals
    * @param setOff  Global clause index where generated literals begin
    * @return Clause-level LiteralTransformation instance
    */
  def LiteralInfo2LiteralTransforamtion(litInfo: Seq[LiteralInfo], setOff: Int) = {
    Out.lp_debug_info(s"generating LiteralTransformation for $litInfo, using set-off $setOff")
    litInfo.zipWithIndex.foldLeft[LiteralTransformation](LiteralTransformation()) { (acc, infoIdx) =>
      // the first transofrmation we handle will affect the leftmost one of the generated literals
      val newIdx = setOff + (infoIdx._2)
      if (infoIdx._1.flip) LiteralTransformation(acc.flippedLits :+ newIdx, acc.normalizedEq)
      else if (infoIdx._1.normalize.isDefined) LiteralTransformation(acc.flippedLits, acc.normalizedEq :+ (newIdx, infoIdx._1.normalize.get))
      else acc
    }
  }

  /**
    * verifyLiteralNormalisazion — generate Lambdapi rewrite tactic applications to verify Leo’s
    * literal normalisation as implicit transformations during other steps.
    *
    * Context (where it is used):
    * Leo may additionally perform *literal-level normalisation* on some equational literals
    * while performing a given infernce rule. Two operations are possible:
    *
    *   - "eq normalisation": turning an equation/inequality into a canonical boolean shape
    *     (Top/Bot cases), sometimes requiring an extra symmetry flip depending on whether the
    *     normalisation happens on the left or right side (see `LitNorm.{TopL,TopR,BotL,BotR}`).
    *
    *   - "flip": applying equality symmetry to selected equational literals (recorded in
    *     `addInfo.flippedLits`), so that the clause literals match Leo’s post-step orientation.
    *
    * What this function returns:
    * A sequence of `Rewrite` proof scripts that rewrite exactly the affected literals in the
    * clause. Rewriting is done via clause-patterns generated by
    * `PatternBuilder.generateClausePattern`, targeting literal positions with`PatternInfo`.
    *
    * Implementation outline:
    * 1) For each entry in `addInfo.normalizedEq`, emit a rewrite using the corresponding theorem
    * (`lpSimp_eqTop` / `lpSimp_eqBot`). If the normalisation mode requires a symmetry flip
    * (TopL/BotL), record that position in `newFlipSteps`.
    * 2) Combine recorded flips (`addInfo.flippedLits`) with flips induced by normalisation
    * (`newFlipSteps`). Assert that these sets do not overlap (they correspond to disjoint
    * normalisation scenarios).
    * 3) If flips are required, emit a single clause-level rewrite using `eqSym`, targeting all
    * relevant positions at once.
    *
    * Indexing / bookkeeping:
    * - The transformation info refers to literal positions in the *child* clause.
    * - During reconstruction we may have inserted or permuted literals; `old2NewIdx` is used to
    * map recorded positions to the current clause layout.
    * - `goalLits` is the child clause used to recover the polarity for pattern generation.
    *
    * @param addInfo   Literal-level transformation info recorded by DetUniSimp (normalisations + flips).
    * @param goalLits  The target clause literals (typically `child.cl.lits`) used for polarity lookup.
    *                  These are the literals that are in the goal, i.e. the one that the rewrite tactic
    *                  is to be applied to.
    * @param clauseLen Total number of literals in the clause at the point the rewrites will be applied
    *                  (e.g. `ctxt.substClauseLen` in the substitution subproof).
    * @param idxMap    The literal-Indices given in addInfo still refer to the index in the orginal
    *                  child clause. As previous steps in the verification may already have changed
    *                  the positions, it may be necessary to map the original position to the new one.
    *                  If no operations have been performed that effected the position, an identity map
    *                  can simply be used here.
    * @return Sequence of `Rewrite` scripts to be inserted before the substitution refine step.
    */
  def verifySubstitutionLiteralNormalisazion(addInfo: LiteralTransformation, goalLits: Seq[Literal], clauseLen: Int, idxMap: Int => Int = identity): Seq[Rewrite] = {
    // todo: maybe change to not take a list of goal lits but just a map of the indices to the polarities?

    // helper for looking up the mapped index and polarity of a given index
    def generatePatternInfo(id: Int): PatternBuilder.PatternInfo = {
      val idxInGoal = idxMap(id)
      if (goalLits.isDefinedAt(idxInGoal)) PatternBuilder.PatternInfo(idxInGoal, None, goalLits(id).polarity)
      else {
        Out.lp_debug_info(s"Warning: trying to generate pattern for literal with index $id, which is out of bounds for goal literals. Using default polarity positive")
        PatternBuilder.PatternInfo(idxInGoal, None, true)
      }
    }

    // flipping may be necessary either in cases where normalisazion is applied, or in cases where only flipping was used
    var newFlipSteps: Seq[Int] = Seq.empty

    // first, handle the literals that need normalisazion
    val maybeNormalizeSteps: Seq[Rewrite] = if (addInfo.normalizedEq.nonEmpty) {
      Out.lp_debug_info(s"need to normalize: ${addInfo.normalizedEq}")
      addInfo.normalizedEq.map { pair =>
        val (pos, normMode) = pair
        val rule: LpTerm[Level.Meta] = normMode match {
          case LitNorm.TopL => newFlipSteps = newFlipSteps :+ pos; lpSimp_eqTop
          case LitNorm.TopR => lpSimp_eqTop
          case LitNorm.BotL => newFlipSteps = newFlipSteps :+ pos; lpSimp_eqBot
          case LitNorm.BotR => lpSimp_eqBot
          case LitNorm.NegBotL => newFlipSteps = newFlipSteps :+ pos; lpSimp_negEqBot
          case LitNorm.NegBotR => lpSimp_negEqBot
        }
        val patternInfo = generatePatternInfo(pos)
        val pattern = PatternBuilder.generateClausePattern(Seq(patternInfo), clauseLen)
        Rewrite(Some(pattern), rule, Side.Left)
      }
    } else Seq.empty

    // sanity check: we ony need to flip literals that are equational and we only need to rewrite literals to an euational form if they are non-equational. Therefore, there can never be an overlap between the two
    assert(addInfo.flippedLits.intersect(newFlipSteps).isEmpty, s"Error in Lambdapi Encoding: Trying to verify literal-normalisazion, but found contradicroty input (${addInfo.flippedLits.intersect(newFlipSteps)})")

    // secondly, all the flip steps are carried out in one rewrite tactic application
    val allFlipSteps = (addInfo.flippedLits ++ newFlipSteps).sorted
    val maybeFlipStep: Seq[Rewrite] = if (allFlipSteps.nonEmpty) {
      Out.lp_debug_info(s"the following literals need to be flipped: $allFlipSteps")
      val flipInfo = allFlipSteps.map(generatePatternInfo)
      val flipPattern = PatternBuilder.generateClausePattern(flipInfo, clauseLen)

      Out.lp_debug_info(s"everything is still okay")
      Seq(Rewrite(Some(flipPattern), eqSym))
    } else Seq.empty

    maybeNormalizeSteps ++ maybeFlipStep
  }

}
