package leo.modules.output.LPoutput.NewLpDatastructures

import leo.datastructures.{Signature, isPropSet}
import leo.datastructures.Signature.Key
import leo.modules.HOLSignature
import leo.modules.HOLSignature._
import leo.modules.output.LPoutput.NewLpDatastructures.lpEncSig._

//////////////////////////////////////////
// Utility for extending the signature originally
// generated by Leo-III with encodigns necessary
// to output the Lambdapi files
//////////////////////////////////////////

/** Map the keys of the Leo-III HOL signature to the qnames used in the Lambdapi encoding */
object tptpConstMappings {

  val leoBaseTy: Map[Key, QName] = Map[Signature.Key,QName](
    HOLSignature.oKey -> QName.local(oTyStr),
    HOLSignature.iKey -> QName.local(iTyStr),
    HOLSignature.intKey -> QName.local(tptpIntStr),
    HOLSignature.ratKey -> QName.local(tptpRationalStr),
    HOLSignature.realKey -> QName.local(tptpRealStr)
  )

  val leoTopBot: Map[Key, QName] = Map[Signature.Key, QName](
    LitTrue.key -> QName.local(topStr),
    HOLSignature.LitFalse.key -> QName.local(botStr))

  val leoTypedConnectives: Map[Key, QName] = Map[Signature.Key, QName](
    HOLSignature.===.key -> QName.local(eqStr)
  )

  val leoBinders: Map[Key, QName] = Map[Signature.Key, QName](
    HOLSignature.Forall.key -> QName.local(forAllStr),
    HOLSignature.Exists.key -> QName.local(exStr),
    HOLSignature.Choice.key -> QName.local(choiceStr)
  )

  val leoUntypedConnectives: Map[Key, QName] = Map[Signature.Key, QName](
    HOLSignature.|||.key -> QName.local(orStr),
    HOLSignature.&.key -> QName.local(andStr),
    HOLSignature.Impl.key -> QName.local(impStr),
    HOLSignature.Not.key -> QName.local(negStr),
    HOLSignature.Impl.key -> QName.local(impStr)
  )

  val leoArithmetic: Map[Key, QName] = Map[Signature.Key, QName](
    HOLSignature.HOLLess.key -> QName.local(tptpLessStr),
    HOLSignature.HOLLessEq.key -> QName.local(tptpLessEqStr),
    HOLSignature.HOLGreater.key -> QName.local(tptpGreaterStr),
    HOLSignature.HOLGreaterEq.key -> QName.local(tptpGreaterEqStr),
    HOLSignature.HOLUnaryMinus.key -> QName.local(tptpUnaryMinusStr),
    HOLSignature.HOLSum.key -> QName.local(tptpSumStr),
    HOLSignature.HOLDifference.key -> QName.local(tptpDifferenceStr),
    HOLSignature.HOLProduct.key -> QName.local(tptpProductStr),
    HOLSignature.HOLQuotient.key -> QName.local(tptpQuotientStr)
  )

  val LeoConstants: Map[Signature.Key, QName] = leoTopBot ++ leoTypedConnectives ++ leoUntypedConnectives ++ leoBinders ++ leoArithmetic
}

/** The signature generated by Leo-III extended with mappings of the keys to the Qnames assigned to symbols in the Lambdapi encoding */
final case class LpSig( orig: Signature,
                        termNames: Map[Key, QName],
                        typeNames: Map[Key, QName],
                        reserved: Set[String])

/** Utility for building a signature for the Lambdapi encoding based on the Leo-III signature */
object LpSig {

  /** Check names against the permitted symbols in Lambdapi and - if necessary - wrap in escape characters */
  private def escapeIfNeeded(raw: String): String =
    if (raw.matches(lpSysStrings.lpAllowedRegEx)) raw
    else s"{|$raw|}"

  /*
  private def freshIfNeeded(name: String, taken: collection.mutable.Set[String]): String = {
    if (!taken.contains(name)) name
    else {
      var i = 1
      var newName = s"${name}_$i"
      while (taken.contains(newName)) {
        i += 1
        newName = s"${name}_$i"
      }
      newName
    }
  }
   */
  // use this for compatibility reasons for now but the commented version above would be nicer...
  /** Generate a fresh name if the currently chosen one is already occupied */
  private def freshIfNeeded(name: String, taken: collection.mutable.Set[String]): String = {
    if (!taken.contains(name)) name
    else {
      val newName = s"${name}_"
      freshIfNeeded(newName, taken)
    }
  }

  /** Check if given name is Lambdapi-safe and modify it if necessary */
  private def safeName(base0: String, reserved: collection.mutable.Set[String]): String = {
    val base = escapeIfNeeded(base0)
    if (!reserved(base)) {
      base
    }
    else {
      val fresh = freshIfNeeded(base0, reserved)
      val safeFresh = escapeIfNeeded(fresh)
      safeFresh
    }
  }

  /**
    * Build an LP-safe signature mirror.
    *
    * @param orig The original signature generated by Leo-III
    * @return signature extended with mappings necessary for the Lambdapi encoding
    * */
  def fromLeo(orig: Signature): LpSig = {
    // Start with LP-reserved names (keywords + all library glyph spellings)
    val res = collection.mutable.Set.empty[String]
    res ++= lpSysStrings.reserve

    // Produce term names
    val termNames: Map[Signature.Key, QName] = {
      orig.allConstants.map { k =>
        val meta = orig.meta(k)
        if (tptpConstMappings.LeoConstants.keySet.contains(meta.key)) {
          k -> tptpConstMappings.LeoConstants(meta.key)
        }
        else {
            val raw = meta.name
            val safe = safeName(raw, res)
            // Skolems are always local
            val qn = if (isPropSet(Signature.PropSkolemConstant, meta.flag))
              QName(None, Name(safe))
            else
              QName(Some(Prefix.Sig), Name(safe))
            k -> qn
          }
      }.toMap
    }

    // Produce type names
    val typeNames: Map[Signature.Key, QName] = {
      orig.typeConstructors.map { k =>
        val meta = orig.meta(k)
        if (tptpConstMappings.leoBaseTy.keySet.contains(meta.key))
          {k -> tptpConstMappings.leoBaseTy(meta.key)}
        else{
          val raw = meta.name
          val safe = safeName(raw, res)
          val qn = QName(Some(Prefix.Sig), Name(safe))
          k -> qn
        }
      }.toMap
    }

    LpSig(orig, termNames, typeNames, res.toSet)
  }
}

